#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.5.4
dpkg-maintscript-helper symlink_to_dir /usr/share/doc/libnfnetlink0-dbg /usr/share/doc/libnfnetlink0 1.0.1-2~ libnfnetlink0-dbg -- "$@"
# End automatically added section
